
datatoggle:
  webapp_url: https://app.datatoggle.com
  destination_scripts_url_prefix: https://cdn.jsdelivr.net/npm/@datatoggle
  db_connection: r2dbc:gcp:postgres://${DB_USER}:${DB_USER_PWD}@${DB_URL}/postgres?schema=datatoggle_server
