

datatoggle:
  cloudflare:
    account_id: ${CLOUDFLARE_ACCOUNT_ID}
    configs_namespace_id: ${CLOUDFLARE_CONFIGS_NAMESPACE_ID}
    api_token: ${CLOUDFLARE_API_TOKEN}
  server_analytics_token: ${SERVER_ANALYTICS_TOKEN}

