-- All tables has
-- id: primary_key, int, for join requests and foreign keys, should not be exposed to service clients
-- uri: unique identifier, immutable, can be exposed
-- creation_datetime: for diagnostics


CREATE TABLE datatoggle_server.user_account(
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   uri TEXT NOT NULL UNIQUE,
   firebase_auth_uid TEXT NOT NULL UNIQUE, -- for connection from customer dashboard
   creation_datetime TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE datatoggle_server.workspace(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uri TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    creation_datetime TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE datatoggle_server.workspace_member(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES datatoggle_server.workspace(id),
    user_account_id BIGINT NOT NULL REFERENCES datatoggle_server.user_account(id),
    creation_datetime TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UNIQUE(workspace_id, user_account_id)
);


CREATE TABLE datatoggle_server.workspace_source(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uri TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  api_key UUID NOT NULL UNIQUE, -- for connection from user
  workspace_id BIGINT NOT NULL REFERENCES datatoggle_server.workspace(id),
  creation_datetime TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);


CREATE TABLE datatoggle_server.workspace_destination(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enabled BOOLEAN NOT NULL,
    workspace_id BIGINT NOT NULL REFERENCES datatoggle_server.workspace(id),
    destination_uri TEXT NOT NULL, -- reference code
    destination_specific_config JSONB NOT NULL,
    last_modification_datetime TIMESTAMPTZ NOT NULL,
    creation_datetime TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UNIQUE(workspace_id, destination_uri) -- for now, it's not possible to have several time the same destination
);


CREATE TABLE datatoggle_server.workspace_connection(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id BIGINT NOT NULL REFERENCES datatoggle_server.workspace(id),
  source_id BIGINT NOT NULL REFERENCES datatoggle_server.workspace_source(id),
  destination_id BIGINT NOT NULL REFERENCES datatoggle_server.workspace_destination(id),
  creation_datetime TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UNIQUE(source_id, destination_id)
);


CREATE TABLE datatoggle_server.event(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_uri TEXT NOT NULL,
    event_name TEXT NOT NULL,
    event_data JSONB NOT NULL,
    creation_datetime TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

