name: deploy-to-prod
on: workflow_dispatch
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      #- run: ./gradlew build
      #- run: ./gradlew test
      #- run: ./gradlew ktlintCheck
      # authenticate to gcloud and setup gcloud CLI
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - uses: 'google-github-actions/setup-gcloud@v0'
      - run: 'gcloud info'
