name: deploy-to-prod
on: workflow_dispatch
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: 'mkdir ./src/main/resources/secrets && echo "$firebase_private_key_json" > ./src/main/resources/secrets/firebase_private_key.json'
        env:
          firebase_private_key_json: ${{ secrets.FIREBASE_PRIVATE_KEY }}
      - run: ./gradlew build
      - run: ./gradlew test
      - run: ./gradlew ktlintCheck
      # authenticate to gcloud and setup gcloud CLI
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - uses: 'google-github-actions/setup-gcloud@v0'
      - run: ./.github/scripts/deploy_to_cloud.sh
